### PR TITLE
Add a GitHub action.

### PR DESCRIPTION
**Pull request by StevenDufresne**
Since we already have linting & formatting set up, I think we should run it on GitHub.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@StevenDufresne looks like some conflicts plus the check is failing, are you able to check those out?

**Comment by StevenDufresne** [comment]
@jeffpaul Hey! I've fixed the conflicts. I'm probably not the best to speak on the PHP linting errors although don't mind fixing them. Before I do so, @coreymckrill can you give the results a quick check to make sure they are legitimate.

https://github.com/WordPress/revisions-extended/runs/6150427334?check_suite_focus=true

**Comment by coreymckrill** [comment]
@StevenDufresne there are, indeed, linting errors. It looks like I never actually checked the linter after setting up the config file for it? 😬 

The linter rules here seem rather picky. I suspect if we added the shared configs from [repo tools](https://github.com/WordPress/wporg-repo-tools/) there would still be some errors, but fewer of them to fix. Not sure if that should be done in this PR or a separate one, though.

**Comment by jeffpaul** [comment]
@coreymckrill no argument from me in making that adjustment in this PR

**Comment by coreymckrill** [comment]
@StevenDufresne I went ahead and fixed up the php stuff, but it looks like there's a JS linting error as well. Can you handle that one?

**Comment by StevenDufresne** [comment]
Yep, I'll take care of it. Thanks for the PHP fixes.

**Comment by StevenDufresne** [comment]
@coreymckrill I think I got all the lint issues kicked up by the new tooling. Seems to be failing on PHP again :).

**Comment by coreymckrill** [comment]
D'oh. I'll take a look.

**Comment by coreymckrill** [comment]
💥

**Pull request merged**
